import {  createSlice } from '@reduxjs/toolkit';

const initialUser = localStorage.getItem('user') ? JSON.parse(localStorage.getItem('user')) : null;



// reducer are the functions that act on the data and change the data on global state
export const userSlice = createSlice({
  name: 'user',
  initialState:{
    user: initialUser|| null,
  },
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    login:(state, action)=>{
      state.user = action.payload;
    },
    logout:(state)=>{
      state.user = null;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
 
});

export const { login, logout } = userSlice.actions;


// Note here state is whole store and user is the slice of the store and next user is attribute of the user
export const selectUser = (state) => state.user.user;



export default userSlice.reducer;
